name: rby
description: An opinionated widgets & utilities library
version: 0.0.1
homepage: https://github.com/robertodoering/rby.dart
publish: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  http: ^1.1.0
  intl: ^0.18.1
  logging: ^1.2.0
  material_color_utilities: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
